version: '2'

services:
    nginx:
        build: nginx/.
        ports:
            - 80:80

        restart: always
        networks:
            vpcbr:
                ipv4_address: 10.5.0.2

    idjsonweb0:
        volumes:
          - /mnt/efs:/app/registro
        ports:
            - 5000:5000
        depends_on:
            - nginx
        build: app/.
        restart: always
        networks:
            vpcbr:
                ipv4_address: 10.5.0.3

    idjsonweb1:
        volumes:
          - /mnt/efs:/app/registro
        ports:
            - 5002:5000
        depends_on:
            - nginx
        build: app/.
        restart: always
        networks:
            vpcbr:
                ipv4_address: 10.5.0.4


networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
