version: '2'

services:

    idjsonweb2:
        volumes:
          - /mnt/efs:/app/registro
        ports:
            - 5000:5000

        build: app/.
        restart: always
        networks:
            vpcbr:
                ipv4_address: 10.5.0.5

    idjsonweb3:
        volumes:
          - /mnt/efs:/app/registro
        ports:
            - 5001:5000

        build: app/.
        restart: always
        networks:
            vpcbr:
                ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
